Fixed ordering of quotation marks next to punctuation and symbols
engage-xr/RTLTMPro pull request #4
Opened 2024-06-17 17:03 UTC by matthew-ivre

Test strings:
![image](https://github.com/engage-xr/RTLTMPro/assets/98825945/afd360c3-0a09-47bb-a28f-56b04d60dd63)

2024-06-18 09:41 UTC, matthew-ivre commented
Extended tests - before (issues highlighted):
![image](https://github.com/engage-xr/RTLTMPro/assets/98825945/83da2fcd-f170-4f37-b83d-ba341179e07d)

After:
![image](https://github.com/engage-xr/RTLTMPro/assets/98825945/0c374ef4-aed5-4b6d-beb7-9ad0260ea783)

2024-06-18 09:50 UTC, BenIVRE requested changes
I think it would be good to include your test cases as actual unit tests. Let me know if you want a hand setting those up.

2024-06-18 09:50 UTC, BenIVRE commented on Assets/RTLTMPro/Scripts/Runtime/LigatureFixer.cs
> +                            isAfterQuote && isSpecialPunctuation)
Double checking `isSpecialPunctuation` can be changed to `if (isSpecialPunctuation && (isAfterNumber || isAfterQuote))`

2024-06-18 10:07 UTC, ruben-ivre approved these changes

2024-06-18 10:07 UTC, ruben-ivre commented on Assets/RTLTMPro/Scripts/Runtime/TextUtils.cs
> +            return input is '"' or '�' or '�';
I would rather include those special chars as \uXXXX format rather than trust file encoding.

2024-06-18 13:27 UTC, matthew-ivre commented on Assets/RTLTMPro/Scripts/Runtime/LigatureFixer.cs
> +                            isAfterQuote && isSpecialPunctuation)
Sure. Looks cleaner. Implemented in [9e13f89](https://github.com/engage-xr/RTLTMPro/pull/4/commits/9e13f896ba65ec6a957ef31d28e0ad77499cda2e)

2024-06-18 13:31 UTC, matthew-ivre commented on Assets/RTLTMPro/Scripts/Runtime/TextUtils.cs
> +            return input is '"' or '�' or '�';
Makes sense. The original project declared character constants in 0xXXXX format, but I'm presuming there's no functional difference. Implemented in [9e13f89](https://github.com/engage-xr/RTLTMPro/pull/4/commits/9e13f896ba65ec6a957ef31d28e0ad77499cda2e)

2024-06-18 13:33 UTC, ruben-ivre approved these changes

2024-06-18 13:34 UTC, ruben-ivre commented on Assets/RTLTMPro/Scripts/Runtime/TextUtils.cs
> +            return input is '"' or '�' or '�';
It's less risky using numerical values, as you can accidentally break file encoding thus breaking those chars, but you cannot accidentally break numerical values.

2024-06-18 13:43 UTC, matthew-ivre commented on Assets/RTLTMPro/Scripts/Runtime/TextUtils.cs
> +            return input is '"' or '�' or '�';
Sorry, yeah, I meant I presumed there was no difference in this situation between (char)0x00AB and '\u00AB'.

2024-06-18 13:58 UTC, ruben-ivre commented on Assets/RTLTMPro/Scripts/Runtime/TextUtils.cs
> +            return input is '"' or '�' or '�';
No, there's no diff, using numeric constants casted to char or directly using char literals makes no diff. https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/char#literals

2024-06-21 07:27 UTC, daniel-ivre approved these changes

2024-06-21 07:33 UTC, juanma-ivre approved these changes

2024-06-21 08:19 UTC, BenIVRE approved these changes

2024-06-21 08:25 UTC, merged