Fix for period following Latin text in Arabic string
engage-xr/RTLTMPro pull request #7
Opened 2024-07-16 10:08 UTC by matthew-ivre

https://vreducation.atlassian.net/browse/EN-43419

Corrects issue highlighted in orange:
![image](https://github.com/user-attachments/assets/a9fc9a42-4890-4ca7-91da-6600ca85f6d1)

Result:
![image](https://github.com/user-attachments/assets/ff439751-0c6f-4fb2-9305-eec3adac2c60)

2024-07-16 10:11 UTC, matthew-ivre commented
Continuing to update both the project and UPMPackage folders until we decide on how to restructure.

2024-07-16 10:13 UTC, matthew-ivre commented
All tests passed.

2024-07-16 10:14 UTC, daniel-ivre approved these changes

2024-07-16 10:21 UTC, juanma-ivre approved these changes

2024-07-16 10:22 UTC, ruben-ivre requested changes

2024-07-16 10:22 UTC, ruben-ivre commented on UPMPackage/Tests/EngageOrderingTests.cs
We have a warning that this script is missing is .meta companion, it's not a big deal, but would be nice if we can fix it.

2024-07-19 10:23 UTC, matthew-ivre commented on UPMPackage/Tests/EngageOrderingTests.cs
Sorry, I missed this comment. I've added the .meta files.

2024-07-19 10:32 UTC, ruben-ivre approved these changes

2024-07-23 09:06 UTC, merged